### ISSUE TITLE
Add Code of conduct file

### ISSUE THREAD

**Issue by KerinPithawala** [mexili/cssify#6]
**Is your feature request related to a problem? Please describe.**
No problem in repo.

**Describe the solution you'd like**
I would like to add a file for a code of conduct. Because most of open source projects have this feature.

**Describe alternatives you've considered**
Adding code of conduct in README.md

**Additional context**
This can help to enhance documentation. Can I work on this issue?

**Comment by yashgautam9274** [comment]
I want to work on this issue

**Comment by KerinPithawala** [comment]
Can I work on this issue?

**Comment by sansyrox** [comment]
@yashgautam9274 , @Kerveyfelix claimed it first. So, she/he has been assigned this issue.

**Comment by sansyrox** [comment]
Yes @Kerveyfelix , you can go ahead!
